### ISSUE TITLE
fix buffering patch

### ISSUE THREAD

**Issue by 9viz** [9viz/bar#1]
re: jaimet

i might not be able to add it in just yet because i recently changed how lemonbar reads the text it needs to display. since i dont have much time rn (busy with exams), i might not be able to modify the patch and apply it. you might have to wait around 2 months.

i did, however, consider patching the fix in but didn't get around to it. so it's definitely on my bucket list.

sorry for any inconvenience if caused

**Comment by jaimet** [comment]
@vizs No problem at all. Thank you, both for responding to my original issue, and also for enabling issues on this repo.

Re the patch, yeah, I came to exactly the same conclusion as you i.e. that [this patch](https://github.com/vizs/bar/commit/6e35ea753ebc87980a1e34f252865ae69a2e7576) results in a merge conflict with [the bar buffering patch](https://github.com/shdown/bar/commit/eb0e9e79b9a35c3093f6e2e90d9fbd175a2305ef.patch)).

Re the delay, that's fine, I understand. If I can find a couple of hours in the near future, I'll have a go at resolving the merge conflict myself, and I'll update this issue with any progress. Thank you again for considering this (I know that bar's development has been difficult at times!), and good luck with your exams.

Jaime

**Comment by 9viz** [comment]
@jaimet If you do not care about the recent changes I made to the bar, you can use this fork instead https://github.com/seitokaichou/bar. It's essentially everything I added (except the new read-from-file thing) plus the buffering patch.

I hope this is enough and will close the issue if you think the fork is satisfactory.

**Comment by jaimet** [comment]
> @jaimet ... you can use this fork instead https://github.com/seitokaichou/bar...

@vizs Wow - good find! (I used both http://gitpop2.herokuapp.com and https://techgaun.github.io/active-forks/index.html to look for forks, but as neither of them is recursive, I never found seitokaichou's fork).

Thank you for the pointer, and I'm happy to close this now. All the best, J
